keys:
  - &epona "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEOCs1n1/KwAE8NsdGstrDQS7QdUR7cF3hzADGF+DJ5S root@deepwoods"
  - &sonorma "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGqkfb82pspE9A1p3DfWCT1sSUAjxd0ypJbi/m6wsyte sonorma@hellcat"

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - ssh:
          - *sonorma
          - *epona
