name = "deepwoods_fabric"
author = "Sonorma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e3e9d829a7d2d720d2b3315bbc7b1b6396c3c347d755e9056f08717b91dc12c"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
