name = "deepwoods_fabric"
author = "Sonorma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ad72af9d561511da1d672b69a45d4b6a366253eefe0c60b3f97b683b6a17456"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
