name = "deepwoods_fabric"
author = "Sonorma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01bdd4d1547639c6c8f3e8ce7921eaef3a99f84214b7dba0402fa2c5c75cd16a"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
